tests:
	java kmoyennes.KmoyenneTest
mesure:
	java kmoyennes.KMoyennesBenchmark
graphics test:
	java kmoyennes.app.KMoyenneController test
graphics benchmark:
	java kmoyennes.app.KMoyenneController benchmark
